services:
  - type: web
    name: smart-prescription-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
